### ISSUE TITLE
新增需求

### ISSUE THREAD

**Issue by Matear890** [QiuYueBaiJXW/Unikangmusign#8]
背景：公众号：SHWOLXF 上海联通，我的联通 -- 会员中心，第一次需要注册认证（非联通用户也可以注册），这里有个日活动 会员签到和橙豆转盘可以得橙豆，橙豆定期每个月可以领取兑换视频会员(爱奇艺 腾讯 芒果均有)
目的：希望自动能实现日活动 会员签到和橙豆转盘 两个任务，解放双手。

一个月签到下来可以免费得一个月的视频VIP。

**Comment by QiuYueBaiJXW** [comment]
看起来好诱人的样子qwq
不过似乎微信端的东西都不太好搞，
而且最近也没有太多时间，
所以暂时先搁置吧，
麻烦你还得在公主号上动动双手继续签到咯

**Comment by Matear890** [comment]
ok
