### ISSUE TITLE
联通连续签到第七天无积分

### ISSUE THREAD

**Issue by MisterGlasses** [QiuYueBaiJXW/Unikangmusign#9]
大佬知道可能的原因吗？

**Comment by MisterGlasses** [comment]
搞错了action运行正常 是脚本在第七天连续签到时有问题

**Comment by srcrs** [comment]
一天1个积分，一年365个，换不到4块钱花费😂

**Comment by MisterGlasses** [comment]
> 一天1个积分，一年365个，换不到4块钱花费😂

所以我在问连续签到有时没有分啊 连续7天签到是给33分

**Comment by srcrs** [comment]
> > 一天1个积分，一年365个，换不到4块钱花费😂
> 
> 所以我在问连续签到有时没有分啊 连续7天签到是给33分

第七天礼包内容不一定是积分的（你是从哪得知送33积分的？），我查看了一下前面的，都是获得了1G流量日包的礼包。

**Comment by MisterGlasses** [comment]
> > > 一天1个积分，一年365个，换不到4块钱花费😂
> > 
> > 
> > 所以我在问连续签到有时没有分啊 连续7天签到是给33分
> 
> 第七天礼包内容不一定是积分的（你是从哪得知送33积分的？），我查看了一下前面的，都是获得了1G流量日包的礼包。

可能是联通改了 我最后一次获得连续签到积分是在10月13号
![Uploading C3C5DD2B-D1D1-47C4-8E8C-81EC1A6BE8F0.jpeg…]()

**Comment by srcrs** [comment]
> > > > 一天1个积分，一年365个，换不到4块钱花费😂
> > > 
> > > 
> > > 所以我在问连续签到有时没有分啊 连续7天签到是给33分
> > 
> > 第七天礼包内容不一定是积分的（你是从哪得知送33积分的？），我查看了一下前面的，都是获得了1G流量日包的礼包。
> 
> 可能是联通改了 我最后一次获得连续签到积分是在10月13号
> ![Uploading C3C5DD2B-D1D1-47C4-8E8C-81EC1A6BE8F0.jpeg…]()
> 

😂可能是改了，送个月包也好啊，日包作用不大，我今天要不是正好是7天签到，还不知道送有东西。
